### PR TITLE
NIMBUS-228: combobox/lookup search fh fix

### LINKED ISSUE #515: Selected value in drop-down is not retained
Value selection in Dropdown – selected value is not retained.

Have to select multiple times to have the value retained in selection.

### PR DESCRIPTION
**Pull request by lopezton-anthem**
# Description
Fixes #515 

Fixes an issue where `@ComboBox` was not retaining the value and the Search by Lookup function handler was assuming `code` needed to be treated as `String`.

# Type of Change

- [ ] Bug fix

# Test Details

See .java testcases

# Additional Notes

N/A

### CODE REVIEW

**Comment by openanthem-admin** [comment]
You did it @lopezton-anthem!

Thank you for signing the Anthem Opensource Software CLA.

File: nimbus-ui/nimbusui/src/app/components/platform/form/elements/combobox.component.ts [hunk 1]
```diff
@@ -82,7 +82,7 @@ export class ComboBox extends BaseControl<String> {
 
   ngOnInit() {
     this.cb.updateSelectedOption = (val: any): void =>{
-      this.cb.selectedOption = this.cb.findOption(val?val.toString():val, this.cb.optionsToDisplay);
+      this.cb.selectedOption = this.cb.findOption(val, this.cb.optionsToDisplay);
```
Comment (sandeepmantha) [inline nimbus-ui/nimbusui/src/app/components/platform/form/elements/combobox.component.ts]: we can delete the whole ngOnInit() method
